### ISSUE TITLE
(install) command 'arm-linux-gnueabihf-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by ash73** [pimoroni/vl53l1x-python#3]
Hi, I cloned the git repository to my rPi2 and entered:
sudo python setup.py install

After doing some work it generates the error:
command 'arm-linux-gnueabihf-gcc' failed with exit status 1

The full output is:
running install
running bdist_egg
running egg_info
creating python/VL53L1X.egg-info
writing python/VL53L1X.egg-info/PKG-INFO
writing top-level names to python/VL53L1X.egg-info/top_level.txt
writing dependency_links to python/VL53L1X.egg-info/dependency_links.txt
writing manifest file 'python/VL53L1X.egg-info/SOURCES.txt'
reading manifest file 'python/VL53L1X.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'python/VL53L1X.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build
creating build/lib.linux-armv7l-2.7
copying python/VL53L1X.py -> build/lib.linux-armv7l-2.7
running build_ext
building 'vl53l1x_python' extension
creating build/temp.linux-armv7l-2.7
creating build/temp.linux-armv7l-2.7/api
creating build/temp.linux-armv7l-2.7/api/core
creating build/temp.linux-armv7l-2.7/api/platform
creating build/temp.linux-armv7l-2.7/python_lib
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_api_calibration.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_api_calibration.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_core.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_core.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_core_support.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_core_support.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_api_core.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_api_core.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_api_preset_modes.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_api_preset_modes.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_silicon_core.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_silicon_core.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_register_funcs.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_register_funcs.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_wait.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_wait.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_error_strings.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_error_strings.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_api_strings.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_api_strings.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_api.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_api.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/platform/vl53l1_platform.c -o build/temp.linux-armv7l-2.7/api/platform/vl53l1_platform.o
api/platform/vl53l1_platform.c:279:1: warning: multi-line comment [-Wcomment]
 //#define trace_print(level, ...) \
 ^
api/platform/vl53l1_platform.c:283:1: warning: multi-line comment [-Wcomment]
 //#define trace_i2c(...) \
 ^
api/platform/vl53l1_platform.c: In function ‘VL53L1_WaitValueMaskEx’:
api/platform/vl53l1_platform.c:321:2: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
  for(int32_t x = 0; x < attempts; x++){
  ^
api/platform/vl53l1_platform.c:321:2: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

Please help.

**Comment by urbie-mk2** [comment]
@ash73
try before:
export CXXFLAGS="-std=c++11"
export CFLAGS="-std=c99"

**Comment by ash73** [comment]
Still fails with the same error :(

**Comment by Gadgetoid** [comment]
You could try adding it to the Makefile, IE:

```makefile
.PHONY: clean lib

SRC = api
LIB = libvl53l1_api.a
LDFLAGS :=
CFLAGS := -Iapi/core -Iapi/platform -std=c99

SRC_FILES := $(wildcard $(SRC)/*/*.c)
SRC_FILES := $(wildcard $(SRC)/*/*.c)
OBJ_FILES := $(patsubst $(SRC)/*/*.c,$(SRC)/*/%.o,$(SRC_FILES))

$(LIB): $(OBJ_FILES)
	$(CC) $(LDFLAGS) $(CFLAGS) -fPIC -shared -o $@ $^

$(SRC)/%.o: $(SRC)/%.c
	$(CC) $(LDFLAGS) $(CFLAGS) -c -o $@ $<

test: test.c
	$(CC) $(CFLAGS) $(LDFLAGS) -Lvl53l1_api -o test test.c
```

**Comment by ash73** [comment]
Still fails with the same error. Am I missing some dependencies?

**Comment by Gadgetoid** [comment]
You could possibly cheat and edit `api/platform/vl53l1_platform.c` to remove the declaration outside of the for loop.

```
int32_t x;
for(x = 0; x < attempts; x++){
```

You're not missing a dependency, just my Makefile isn't particularly friendly to your version of GCC (I'm using 6.3.0-18+rpi1+deb9u1).

**Comment by Gadgetoid** [comment]
Curious, that change to the Makefile gets me building with `gcc-4.4`, sure you're changing it in the right place?

**Comment by ash73** [comment]
I copied and pasted your text into the file "Makefile" in the vl53l1x-python folder, I think the only bit that changed was adding -std=c99 to the end of the line starting CFLAGS :=

I looked at api/platform/vl53l1_platform.c but the declaration is different in mine:

	int32_t attempts = timeout_ms / poll_delay_ms;
	for(int32_t x = 0; x < attempts; x++){

Not sure what to change / remove.

**Comment by ash73** [comment]
p.s. gcc --version

gcc (Raspbian 4.9.2-10+deb8u1) 4.9.2

**Comment by Gadgetoid** [comment]
If I install gcc-4.9 and build with `cc=/usr/bin/gcc-4.9 make` then it fails without `-std=c99`, but if I add `-std=c99` back in it works fine. You might be able to `git pull` since I've tweaked this into the Makefile upstream, but it sounds like you're editing in the right place. I'm baffled as to why that flag isn't picked up.

When you run `Make` what does the first line that appears say? It *should* have that flag listed.

As a crude hack you could try `"CC=/usr/bin/gcc-4.9 -std=c99" make` or `"CC=/usr/bin/gcc -std=c99" make`

In your case changing:

```
int32_t attempts = timeout_ms / poll_delay_ms;
for(int32_t x = 0; x < attempts; x++){
```

to

```
int32_t attempts = timeout_ms / poll_delay_ms;
int32_t x;
for(x = 0; x < attempts; x++){
```

*May* work, but it also might just reveal other compiler issues that the `-std=c99` flag should be fixing.

**Comment by ash73** [comment]
I tried again from scratch, deleting the vl53l1x-python folder and re-downloading it, the flag -std=c99 is in Makefile, but it still fails with the same error.

I tried updating api/platform/vl53l1_platform.c as described above, it proceeds but reports several other compiler errors, as you expected.

If I just enter make at the command prompt, it says:
cc  -Iapi/core -Iapi/platform -std=c99 -fPIC -shared -o libvl53l1_api.a api/core/vl53l1_api_core.c api/core/vl53l1_error_strings.c api/core/vl53l1_api.c api/core/vl53l1_core_support.c api/core/vl53l1_wait.c api/core/vl53l1_api_calibration.c api/core/vl53l1_core.c api/core/vl53l1_api_preset_modes.c api/core/vl53l1_api_debug.c api/core/vl53l1_register_funcs.c api/core/vl53l1_api_strings.c api/core/vl53l1_silicon_core.c api/platform/vl53l1_platform.c
api/platform/vl53l1_platform.c: In function ‘VL53L1_WaitMs’:
api/platform/vl53l1_platform.c:294:2: warning: implicit declaration of function ‘usleep’ [-Wimplicit-function-declaration]
  usleep(wait_ms * 1000);
  ^

If I enter make a second time, it says:
make: 'libvl53l1_api.a' is up to date.

As you can see, I don't really know what I'm doing. I can read the sensor on an Arduino anyhow and pass the data to the Pi. Thanks for trying.

**Comment by urbie-mk2** [comment]
@ash73 
Could you create a clean install of your operating system, then compile again and then compare the results ? If it isn't the compiler, maybe it is some modification in the operating system that you are not aware of.

**Comment by Gadgetoid** [comment]
@ash73 this time it has built successfully. The `usleep` error is a warning and not a fatal compilation error. Granted I'm not sure *why* it's undeclared and I need to fix that, but the code should work.

If your C compiler is playing ball now you should run:

```
python setup.py build
```

**Comment by ash73** [comment]
I tried again with a completely fresh install of Raspbian. This time it completed the setup but reported some warnings, see below.

sudo python setup.py install

Output:
running install
running bdist_egg
running egg_info
creating python/VL53L1X.egg-info
writing python/VL53L1X.egg-info/PKG-INFO
writing top-level names to python/VL53L1X.egg-info/top_level.txt
writing dependency_links to python/VL53L1X.egg-info/dependency_links.txt
writing manifest file 'python/VL53L1X.egg-info/SOURCES.txt'
reading manifest file 'python/VL53L1X.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'python/VL53L1X.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build
creating build/lib.linux-armv7l-2.7
copying python/VL53L1X.py -> build/lib.linux-armv7l-2.7
running build_ext
building 'vl53l1x_python' extension
creating build/temp.linux-armv7l-2.7
creating build/temp.linux-armv7l-2.7/api
creating build/temp.linux-armv7l-2.7/api/core
creating build/temp.linux-armv7l-2.7/api/platform
creating build/temp.linux-armv7l-2.7/python_lib
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_api_calibration.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_api_calibration.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_core.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_core.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_core_support.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_core_support.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_api_core.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_api_core.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_api_preset_modes.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_api_preset_modes.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_silicon_core.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_silicon_core.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_register_funcs.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_register_funcs.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_wait.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_wait.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_error_strings.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_error_strings.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_api_strings.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_api_strings.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/core/vl53l1_api.c -o build/temp.linux-armv7l-2.7/api/core/vl53l1_api.o
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c api/platform/vl53l1_platform.c -o build/temp.linux-armv7l-2.7/api/platform/vl53l1_platform.o
api/platform/vl53l1_platform.c:279:1: warning: multi-line comment [-Wcomment]
 //#define trace_print(level, ...) \
 ^
api/platform/vl53l1_platform.c:283:1: warning: multi-line comment [-Wcomment]
 //#define trace_i2c(...) \
 ^
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Iapi/core -Iapi/platform -I/usr/include/python2.7 -c python_lib/vl53l1x_python.c -o build/temp.linux-armv7l-2.7/python_lib/vl53l1x_python.o
python_lib/vl53l1x_python.c: In function ‘initialise’:
python_lib/vl53l1x_python.c:83:12: warning: return from incompatible pointer type [-Wincompatible-pointer-types]
     return dev;
            ^~~
python_lib/vl53l1x_python.c:58:13: warning: unused variable ‘status_int’ [-Wunused-variable]
     int32_t status_int;
             ^~~~~~~~~~
python_lib/vl53l1x_python.c:56:40: warning: unused variable ‘pVersion’ [-Wunused-variable]
     VL53L1_Version_t                  *pVersion   = &Version;
                                        ^~~~~~~~
python_lib/vl53l1x_python.c:54:13: warning: unused variable ‘PhaseCal’ [-Wunused-variable]
     uint8_t PhaseCal;
             ^~~~~~~~
python_lib/vl53l1x_python.c:53:13: warning: unused variable ‘VhvSettings’ [-Wunused-variable]
     uint8_t VhvSettings;
             ^~~~~~~~~~~
python_lib/vl53l1x_python.c:52:13: warning: unused variable ‘isApertureSpads’ [-Wunused-variable]
     uint8_t isApertureSpads;
             ^~~~~~~~~~~~~~~
python_lib/vl53l1x_python.c:51:14: warning: unused variable ‘refSpadCount’ [-Wunused-variable]
     uint32_t refSpadCount;
              ^~~~~~~~~~~~
python_lib/vl53l1x_python.c: In function ‘getDistance’:
python_lib/vl53l1x_python.c:131:18: warning: variable ‘Status’ set but not used [-Wunused-but-set-variable]
     VL53L1_Error Status = VL53L1_ERROR_NONE;
                  ^~~~~~
python_lib/vl53l1x_python.c: In function ‘stopRanging’:
python_lib/vl53l1x_python.c:145:12: warning: ‘return’ with a value, in function returning void
     return VL53L1_StopMeasurement(dev);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
python_lib/vl53l1x_python.c:143:6: note: declared here
 void stopRanging(VL53L1_Dev_t *dev)
      ^~~~~~~~~~~
arm-linux-gnueabihf-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-armv7l-2.7/api/core/vl53l1_api_calibration.o build/temp.linux-armv7l-2.7/api/core/vl53l1_core.o build/temp.linux-armv7l-2.7/api/core/vl53l1_core_support.o build/temp.linux-armv7l-2.7/api/core/vl53l1_api_core.o build/temp.linux-armv7l-2.7/api/core/vl53l1_api_preset_modes.o build/temp.linux-armv7l-2.7/api/core/vl53l1_silicon_core.o build/temp.linux-armv7l-2.7/api/core/vl53l1_register_funcs.o build/temp.linux-armv7l-2.7/api/core/vl53l1_wait.o build/temp.linux-armv7l-2.7/api/core/vl53l1_error_strings.o build/temp.linux-armv7l-2.7/api/core/vl53l1_api_strings.o build/temp.linux-armv7l-2.7/api/core/vl53l1_api.o build/temp.linux-armv7l-2.7/api/platform/vl53l1_platform.o build/temp.linux-armv7l-2.7/python_lib/vl53l1x_python.o -o build/lib.linux-armv7l-2.7/vl53l1x_python.so
creating build/bdist.linux-armv7l
creating build/bdist.linux-armv7l/egg
copying build/lib.linux-armv7l-2.7/vl53l1x_python.so -> build/bdist.linux-armv7l/egg
copying build/lib.linux-armv7l-2.7/VL53L1X.py -> build/bdist.linux-armv7l/egg
byte-compiling build/bdist.linux-armv7l/egg/VL53L1X.py to VL53L1X.pyc
creating stub loader for vl53l1x_python.so
byte-compiling build/bdist.linux-armv7l/egg/vl53l1x_python.py to vl53l1x_python.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying python/VL53L1X.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying python/VL53L1X.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying python/VL53L1X.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying python/VL53L1X.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
writing build/bdist.linux-armv7l/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
VL53L1X: module references __file__
creating dist
creating 'dist/VL53L1X-0.0.1-py2.7-linux-armv7l.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing VL53L1X-0.0.1-py2.7-linux-armv7l.egg
creating /usr/local/lib/python2.7/dist-packages/VL53L1X-0.0.1-py2.7-linux-armv7l.egg
Extracting VL53L1X-0.0.1-py2.7-linux-armv7l.egg to /usr/local/lib/python2.7/dist-packages
Adding VL53L1X 0.0.1 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/VL53L1X-0.0.1-py2.7-linux-armv7l.egg
Processing dependencies for VL53L1X==0.0.1
Finished processing dependencies for VL53L1X==0.0.1

**Comment by Gadgetoid** [comment]
That's just a normal side-effect of my lazy programming ;)

You should be able to `sudo python setup.py install` to install the library and start working from there.

That said, after all this if you're intending to use it with Python on a Raspberry Pi for example you can just "sudo pip install VL53L1X"

**Comment by ash73** [comment]
Thanks very much for your help. I think the main problem was a corrupted Raspbian install on my side, sorry to waste your time. Anyhow it's all working now, thanks again.
