### ISSUE TITLE
output from tof.open()

### ISSUE THREAD

**Issue by cjmair** [pimoroni/vl53l1x-python#47]
Is there any way to stop the printed output from the tof.open() function used in the example ?

**Comment by Gadgetoid** [comment]
These should have been long squashed, by https://github.com/pimoroni/vl53l1x-python/pull/39

How are you building/running, C/Python?

**Comment by cjmair** [comment]
I just installed using the pip commands in the READ.me.
I have just used pip to uninstall and downloaded and built and now I no longer get any text from tof.open()

thanks

**Comment by cjmair** [comment]
Is it possible to get the device info, using python, that was displayed when tof.open() was used ?

**Comment by Gadgetoid** [comment]
Right now it's not possible, but there's no reason it couldn't be added!

**Comment by cjmair** [comment]
Thanks
