### ISSUE TITLE
roi functionality

### ISSUE THREAD

**Issue by chetansarmak** [pimoroni/vl53l1x-python#5]
what`s with the roi function?
I am quiet facing issue with i2cwrite when trying to use roi normally.
Any light on how to use the roi function?

**Comment by ash73** [comment]
I could do with an example of how to configure the ROI if possible too, I'm trying to measure the distance to an object inside a 140mm diameter tube, the standard FoV is 27 deg so I can only measure 30cm, I think the minimum FoV is 15 deg which could reach 50cm. Anyone figured out how to do it?

**Comment by Gadgetoid** [comment]
I haven't looked into ROI yet, but implementing it would require wrapper functions in https://github.com/pimoroni/vl53l1x-python/blob/master/python_lib/vl53l1x_python.c

If anyone has a working example of ROI settings being changed in C for the raw vl53l1x library, I'd be keen to see it.

**Comment by omareldamnhouri** [comment]
Did anyone figured out how the roi functionality works? I am trying to setup 2 roi's on the VL53L1X with the raspberry pi. 

If someone has some example code of how i can use the roi (region of interest) I am really thankful!

Thx in advance

**Comment by Gadgetoid** [comment]
I am unfamiliar with the ROI function or its operation, but it's on my radar. Any findings or feedback here would be helpful!

There is some discussion of region-of-interest here, with respect to potentially identifying the direction in which an object is crossing the sensor: https://forum.arduino.cc/index.php?topic=621855.0
