### ISSUE TITLE
Where is vl51l1x_python.so

### ISSUE THREAD

**Issue by rawatsaurabh** [pimoroni/vl53l1x-python#50]
Sorry this is not an issue  but information on where is vl51l1x_python.so being referred here : 

    files = glob.glob(lib_location + "/vl53l1x_python*.so")

How to build this file?Any Makefile for this?

**Comment by Gadgetoid** [comment]
This is configured by the Python installer as a C extension:

https://github.com/pimoroni/vl53l1x-python/blob/9244e4a760d13bd81745ff779dbe314a9ad953f2/setup.py#L3-L22

**Comment by ghost** [comment]
ok but if we try to run the API from the source , how can me make the .so from the c file? Can you please provide the Make file  for it?
I believe they .so is being created from the files inside the api/ folder ( core and platform) correct?
thanks,
